name: "Flujo CI-Test"
run-name: "Flujo CI-Test"
on:
  push:
    branches: [ master ]
env:
  JAVA_VERSION: 17

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3 #24cb9080177205b6e8c946b17badbe402adc938f #v3: v3.4.0
      - name: "java JDK"  
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: "ejecutar tests unitarios"
        run: "./gradlew clean test --info"
        