name: "Flujo CI-Test"
run-name: "Flujo CI-Test
on:
  push:
    branches: [ master ]
env:
  JAVA_VERSION: 17

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f #v3: v3.4.0
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 'env.JAVA_VERSION'
          cache: 'gradle'
      - name: "gradle build repository"
        run: ./gradlew build --no-daemon